config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_scope :user do
    post '/users/email_available/:email' => 'users/registrations#email_available'
    post '/users/username_available/:username' => 'users/registrations#username_available'
    post '/users/settings' => 'users/sessions#settings', as: 'settings'
    get '/users/set_username' => 'social#set_username', as: "set_username"
    post '/users/set_username' => 'social#post_set_username', as: "post_set_username"
    post '/users/set_return_url' => 'social#set_return_url', as: "set_return_url"
  end

  get '/photos/:photo_id/report' => 'reports#new', as: 'new_photo_report'

  post '/google_token' => 'social#google_token', as: "google_token"

  resources :user_taxon_data, only: [:show]

  root :to => 'taxons#index'

  resources :groups, only: [:index, :show] do
    member do
      get 'next' => 'groups#next'
      post 'next' => 'groups#post_next'
    end
  end

  resources :reports do
    member do
      post 'approve/:report_type' => 'reports#approve', as: 'approve'
      post 'reject/:report_type' => 'reports#reject', as: 'reject'
    end
  end

  resources :photos, only: [:edit, :show, :update, :destroy, :show]

  get '/scoreboard' => 'scoreboard#index', as: 'scoreboard'


  resources :taxons, only: [:show, :index] do
    collection do
      get 'all' => 'taxons#index_all', as: 'all'
      get 'search/:name' => 'taxons#search', as: 'search'
      get 'search' => 'taxons#search'
    end
    member do
      get 'photos/rand' => 'taxons#photos_rand', as: 'rand'
      get 'photos/plenty' => 'taxons#photos_plenty', as: 'plenty'
    end
      resources :regions, only: [:show, :index] do
      member do
        get ':mode' => 'game#game', as: 'game'
        post ':mode' => 'game#guess', as: 'guess'
      end
    end
  end

end

app/models/taxon.rb
class Taxon < ApplicationRecord

  mount_uploader :photo, TaxonPhotoUploader

  belongs_to :taxon, optional: true
  belongs_to :taxon, class_name: 'Taxon', :foreign_key => :root_taxon_id, optional: true

  has_and_belongs_to_many :groups
  has_and_belongs_to_many :regions # Regions the taxon has been seen on herpmapper

  has_many :taxons
  has_many :common_names
  has_many :photos
  has_many :bad_region_reports
  has_many :bad_id_reports

  # Only used on root taxon, these are the regions for a root taxon where there are at least 5 species with photos
  has_and_belongs_to_many :valid_regions, join_table: 'regions_root_taxons', class_name: 'Region'

  enum rank: [:root, :family, :subfamily, :genus, :species]

  scope :species, -> { where(rank: :species) }
  scope :genera, -> { where(rank: :genus) }
  scope :families, -> { where(rank: :family) }
  scope :subfamilies, -> { where(rank: :subfamilies) }
  scope :roots, -> { where(rank: :root) }

  def num_photos
    self.photos.size
  end

  def get_root_txn_rank
    # for root taxons return their proper rank (not root) since we dont' have the entire tree
    if common_name == "Snakes"
      return "Suborder"
    elsif common_name == "Lizards"
      return "Suborder"
    elsif common_name == "Turtles and Tortoises"
      return "Order"
    elsif common_name == "Salamanders"
      return "Suborder"
    elsif common_name == "Worm Lizards"
      return "Clade"
    elsif common_name == "Limbless Amphibians"
      return "Order"
    elsif common_name == "Alligators, Crocodiles, and Caimans"
      return "Order"
    elsif common_name == "Frogs and Toads"
      return "Order"
    else
      raise("That's not a root taxon id:#{id}!")
    end
  end

  before_create :title
  before_create :only_species_have_venomous_tag

  def only_species_have_venomous_tag
    if venomous != nil && rank != 'species'
      raise 'Only species can be tagged as venemous'
    end
  end

  def root
    taxon.nil? ? self : self.taxon.root
  end

  def to_hash
    return {
        id: id,
        name: name,
        taxon_id: taxon_id,
        rank: rank,
        root_taxon_id: root_taxon_id,
        photographed: photographed,
        venomous: venomous,
        common_name: common_name,
    }
  end

  def title
    self.name = self.name.titleize
  end

  def sci_name
    begin
      split = self.name.split(" ")
      first = split[0].titleize
      second = split[1].downcase
      return first + " " + second
    rescue
      return self.name
    end
  end

end

app/controllers/taxons_controller.rb
class TaxonsController < ApplicationController
  before_action :set_taxon, only: [:show, :edit, :update, :destroy, :photos_plenty, :photos_rand]

  def search
    name = params[:name]
    if name != ""
      @taxons = Taxon.all.species.where("lower(name) LIKE ?", '%' + name.downcase + '%').limit 100
      common_names = CommonName.all.where("lower(name) LIKE ?", '%' + name.downcase + '%').limit 100
      taxons = common_names.map { |cn| cn.taxon }
      taxons = taxons.select { |tx| tx.rank == "species" }
      @taxons = @taxons + taxons
      @taxons.uniq
      @taxons = @taxons[0..4]
    else
      @taxons = []
    end
    render 'search', formats: [:json]
  end

  def show
    @taxons = @taxon.taxons
    @phylo = []
    tmp = @taxon
    while !tmp.nil? do
      @phylo << tmp
      tmp = tmp.taxon
    end
    @phylo.reverse!
  end

  def index
    @taxons = [Taxon.find(7), Taxon.find(5), Taxon.find(9), Taxon.find(6)]
  end


  def index_all
    @taxons = Taxon.roots.includes(:common_names)
    render 'index'
  end

  def photos_rand
    photos = @taxon.photos.where(dead: false)
    photo = photos[rand(photos.size - 1)]
    render :json => {id: photo.id, taxon_id: photo.taxon.id, url: photo.image_path.url}
  end

  def photos_plenty
    if Rails.env.development?
      if rand() < 0.2
        return render :head
      end
      sleep rand() * 3
    end
    photos = @taxon.photos.where(dead: false).take(ENV['how_many_photos_is_enough_for_learning_mode'].to_i).map { |p| {id: p.id, taxon_id: p.taxon_id, url: p.image_path.url} }
    render :json => photos

  end

  # def edit
  # end
  #
  # def update
  #   @taxon.update(taxon_params)
  #   redirect_to taxon_path(@taxon)
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_taxon
    return if params[:id] == "search" || params[:all] == "search"
    @taxon = Taxon.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def taxon_params
    params.require(:taxon).permit(:name, :photo)
  end
end

app/views/taxons/_form.html.erb
<%= form_with(model: taxon, local: true) do |form| %>
  <% if taxon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(taxon.errors.count, "error") %> prohibited this user_species_datum from being saved:</h2>

      <ul>
        <% taxon.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/taxons/edit.html.erb
<h1>Editing Taxon</h1>

<%= render 'form', taxon: @taxon %>

app/views/taxons/index.html.erb
<% content_for :head do %>
  <meta property="og:title" content="Herpetology: Learn to identify reptiles and amphibians"/>
  <meta property="og:image" content="<%= @taxons[0].photo.url %>"/>
<% end %>

<% content_for :title do %>
  Pick your Herp
<% end %>

<% content_for :breadcrumb do %>
  <% if current_user %>
    Hi <%= current_user.username %>, welcome back.
  <% else %>
    Practice identifying a herp in your area
  <% end %>
<% end %>


<h2>Pick your Herp</h2>
<ul id="pick_taxons">
  <% @taxons.each do |txn| %>
    <%= link_to taxon_regions_path(txn), class: 'main_link_wrap' do %>
      <li>
        <%= image_tag txn.photo.url %>
        <div class="prebutton">
          <%= button_tag class: 'special' do %>
            <h3><%= txn.common_name %></h3>
          <% end %>
        </div>
      </li>
    <% end %>
  <% end %>
</ul>

<div class="center">
  <% if @taxons.size != Taxon.roots.size %>
    <%= link_to "More", all_taxons_path, class: 'main' %>
  <% else %>
    <%= link_to "Less", taxons_path, class: 'main' %>
  <% end %>
</div>

app/views/taxons/show.html.erb
<% content_for :title do %>
  Learn about <%= @taxon.common_name %> (<%= @taxon.name %>)
<% end %>

<% region_array = []
   cur = @region
   while cur != nil
     region_array << cur
     cur = cur.region
   end
   region_array = region_array.reverse
   region_array = region_array.map {|ra| "<a href='#{game_taxon_region_url(@taxon, ra,"game")}'>#{ra.name}</a>"}.join(" > ")
%>

<% content_for :breadcrumb do %>
  <h2>
    <%= link_to render('statics/world'), root_path %> >
    <%= link_to @taxon.common_name, taxon_path(@taxon) %>
    <% if @taxon.regions.countries.any? %>
      <%= react_component('Subregionbutton', {hide_msg: "Hide Regions", show_msg: "Show Regions", game: false}) %>
    <% else %>> No regions
    <% end %>

  </h2>
<% end %>

<% content_for :subregions do %>
  <%= react_component('Subregions', {taxon_id: @taxon.id, id: nil}) %>
<% end %>

<div id="taxon_show">
  <h1><%= react_component('Name', {commonName: @taxon.common_name, sciName: @taxon.name}) %> </h1>

  <div class="taxon_photo">
    <% if @taxon.rank == "root" %>
      <%= image_tag @taxon.photo.url, alt: "Photo of "+@taxon.name %>
    <% elsif @taxon.photos.where(dead: false).any? %>
      <%= image_tag @taxon.photos.where(dead: false).sample.image_path.url, alt: "Photo of "+@taxon.name %>
    <% else %>
      <p>No photos available. Submit one
        on <%= link_to "Herpmapper", "https://herpmapper.org/taxon/" + @taxon.name.gsub(" ", "_") %></p>
    <% end %>
  </div>


</div>