config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_scope :user do
    post '/users/email_available/:email' => 'users/registrations#email_available'
    post '/users/username_available/:username' => 'users/registrations#username_available'
    post '/users/settings' => 'users/sessions#settings', as: 'settings'
    get '/users/set_username' => 'social#set_username', as: "set_username"
    post '/users/set_username' => 'social#post_set_username', as: "post_set_username"
    post '/users/set_return_url' => 'social#set_return_url', as: "set_return_url"
  end

  get '/photos/:photo_id/report' => 'reports#new', as: 'new_photo_report'

  post '/google_token' => 'social#google_token', as: "google_token"

  resources :user_taxon_data, only: [:show]

  root :to => 'taxons#index'

  resources :groups, only: [:index, :show] do
    member do
      get 'next' => 'groups#next'
      post 'next' => 'groups#post_next'
    end
  end

  resources :reports do
    member do
      post 'approve/:report_type' => 'reports#approve', as: 'approve'
      post 'reject/:report_type' => 'reports#reject', as: 'reject'
    end
  end

  resources :photos, only: [:edit, :show, :update, :destroy, :show]

  get '/scoreboard' => 'scoreboard#index', as: 'scoreboard'


  resources :taxons, only: [:show, :index] do
    collection do
      get 'all' => 'taxons#index_all', as: 'all'
      get 'search/:name' => 'taxons#search', as: 'search'
      get 'search' => 'taxons#search'
    end
    member do
      get 'photos/rand' => 'taxons#photos_rand', as: 'rand'
      get 'photos/plenty' => 'taxons#photos_plenty', as: 'plenty'
    end
      resources :regions, only: [:show, :index] do
      member do
        get ':mode' => 'game#game', as: 'game'
        post ':mode' => 'game#guess', as: 'guess'
      end
    end
  end

end

app/models/report.rb
class Report < ApplicationRecord
  self.abstract_class = true

  def self.all_reports
    reports = BadIdReport.all.to_a
    reports.concat(DeadHerpReport.all.to_a)
    reports.concat(NoHerpReport.all.to_a)
    reports.concat(VenomReport.all.to_a)
    reports.concat(BadRegionReport.all.to_a)
  end

  def self.pending
    self.all_reports.select { |r| r.handled == false}
  end


  # All implentations of the abstract class have the following columns
  # - timestamps
  # - handled_by: user
  # - created_by: user
  # - handled: bool

  def approve(approver)
    self.handled_by_id = approver.id
    self.approved = true
    self.handled = true
    self.save!
  end

  def reject(rejecter)
     self.handled_by_id = rejecter.id
     self.approved = false
     self.handled = true
     self.save!
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :contributor_only, only: [:edit, :update, :index, :destroy, :approve, :reject]
  before_action :set_report, only: [:show, :edit, :update, :destroy, :approve, :reject]

  # POST /reports/1/approve
  def approve
    puts "report:"
    puts @report.inspect
    # begin
    @report.approve(current_user) # Method on teh sub classes
    @report.handled = true # Action was taken by mod
    @report.approved = true # User was correct in their suggestion
    @report.handled_by_id = current_user.id
    @report.save!
    return render :json => {msg: 'Approved'}
    # rescue => e
    #   @report.handled = false
    #   @report.handled_by = nil
    #   puts e.inspect
    #   return render :json => {msg: "Failed"}, :status => :bad_request
    # end
  end

  # POST /reports/1/reject
  def reject
    @report.handled = true # Action was taken by mod
    @report.approved = false # User was incorrect
    @report.save!
    render :json => {msg: 'Rejected'}
  end

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.pending
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @photo = Photo.find(params[:photo_id])
    @taxon = @photo.taxon
    @venomous = "unknown"
    @venomous = "venomous" if @taxon.venomous == true
    @venomous = "nonvenomous" if @taxon.venomous == false
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    type = params[:type] # dead_herp_report, bad_id_report, venom_report, no_herp_report
    case type
    when "DeadHerpReport"
      @report = DeadHerpReport.new(dead_herp_params)
    when "BadIdReport"
      begin
        bdp = bad_id_params
      rescue => e
      end
      @report = BadIdReport.new(bdp)
    when "VenomReport"
      @report = VenomReport.new(venom_params)
      puts "Created venom report"
      puts venom_params.inspect
      puts @report.inspect
    when "NoHerpReport"
      @report = NoHerpReport.new(no_herp_params)
    when "BadRegionReport"
      @report = BadRegionReport.new(bad_region_params)
    end
    if current_user
      @report.created_by_id = current_user.id
      if current_user.admin_or_contributor?
        @report.approve(current_user)
      end
    end


    respond_to do |format|
      if @report.save
        unless params[:no_flash]
          if @report.approved
            flash[:notice] = "Report successfully created, and automatically accepted, thank you!"
          else
            flash[:notice] = "Report successfully created, thank you!"
          end
        end
        format.json { render json: {msg: 'Successfully created report'}, status: :created }
        format.html { redirect_back fallback_location: "/" }
      else
        format.json { render json: @report.errors, status: :unprocessable_entity }
        format.html { redirect_back fallback_location: "/" }
      end
    end


  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_report
    case params[:report_type]
    when "DeadHerpReport"
      @report = DeadHerpReport.find(params[:id])
    when "BadIdReport"
      @report = BadIdReport.find(params[:id])
    when "VenomReport"
      @report = VenomReport.find(params[:id])
    when "NoHerpReport"
      @report = NoHerpReport.find(params[:id])
    when "BadRegionReport"
      @report = BadRegionReport.find(params[:id])
    end
  end


  def dead_herp_params
    params.require(:photo_id)
    a = Hash.new
    a[:photo_id] = params[:photo_id]
    return a
  end

  def bad_id_params
    bad_id_params = {:taxon_id => params[:taxon_id], :photo_id => params[:photo_id]}
    return bad_id_params
  end

  def venom_params
    venom_p = {:taxon_id => Photo.find(params[:photo_id]).taxon.id, :venomous => params[:venomous]}
    puts "venom_p:"
    puts venom_p
    return venom_p
  end

  def no_herp_params
    params.require(:photo_id)
    a = Hash.new
    a[:photo_id] = params[:photo_id]
    return a
  end

  def bad_region_params
    params.require(:region_id)
    params.require(:taxon_id)
    prms = Hash.new
    prms[:region_id] = params[:region_id].to_i
    prms[:taxon_id] = params[:taxon_id].to_i
    return prms
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<% content_for :title do
  "Reports (#{Report.all.pending.size})"
end %>
<% content_for :breadcrumb do
  "#{Report.all.pending.size} Pending Reports"
end %>
<h2>Reports</h2>

<div class="center">
  <div>
    <% if @reports.size == 0 %>
      <br/>
      <h4>No Reports</h4>

    <% end %>
    <% @reports.each do |report|
      component_params = Hash.new
      component_params[:reportId] = report.id
      component_params[:approveUrl] = approve_report_url(report,report.class.name)
      component_params[:rejectUrl] = reject_report_url(report,report.class.name)

      unless report.created_by_id.nil?
        component_params[:userId] = User.find(report.created_by_id).id
        component_params[:userUsername] = User.find(report.created_by_id).username
        component_params[:userTotal] = User.find(report.created_by_id).total_seen
        component_params[:userSciAcc] = User.find(report.created_by_id).accuracy_scientific.round(3)
        component_params[:userComAcc] = User.find(report.created_by_id).accuracy_common.round(3)
      end

     case report.class.name
      when "DeadHerpReport"
        component_params[:deadHerp] = true
        component_params[:photoUrl] = report.photo.image_path.url
      when "BadIdReport"

        component_params[:currentTaxonCommon] = report.photo.taxon.common_name
        component_params[:currentTaxonSci] = report.photo.taxon.sci_name
        component_params[:newTaxonCommon] = report.taxon.common_name
        component_params[:newTaxonSci] = report.taxon.sci_name
        component_params[:photoUrl] = report.photo.image_path.url
      when "VenomReport"
        component_params[:photoUrl] = report.taxon.photos[0].image_path.url
        component_params[:venomous] = report.venomous
        component_params[:currentTaxonCommon] = report.taxon.common_name
        component_params[:currentTaxonSci] = report.taxon.sci_name
      when "NoHerpReport"
        component_params[:photoUrl] = report.photo.image_path.url
        component_params[:noHerp] = true
      when "BadRegionReport"
        component_params[:photoUrl] = report.taxon.photos[0].image_path.url
        component_params[:taxon] = report.taxon
        component_params[:region] = report.region
        component_params[:badRegion] = true

      end
       %>
      <%= react_component("Handlereport", component_params) %>
    <% end %>


  </div>
</div>

app/views/reports/new.html.erb
<% content_for :title do %>
  Make a Report
<% end %>

<% content_for :breadcrumb do %>
  Report: <%= @taxon.sci_name %> -- <%= @taxon.common_name.name %>
<% end %>


<div class="center">

  <div>
    <h2>New Report</h2>

    <% report = @report %>

    <%= react_component('Report', {url: @photo.image_path.url, venomous: @venomous, photo_id: @photo.id, options: Taxon.all.species.pluck(:name) } ) %>

  </div>
</div>

app/views/reports/show.html.erb
<% content_for :breadcrumb do %>
  Report of <%= @report.photo.taxon.name %> <%= "by #{@report.created_by.username if @report.created_by}" %>
<% end %>

<% content_for :title do "Report" end %>

<%= react_component('Zoom', url: @report.photo.image_path.url, no_text: true) %>

<div class="center">
  <div>
<h3>Issues</h3>

<% if @report.venomous %>
  <p>
    <strong>This species should be marked as:</strong>
    <%= @report.venomous %>
  </p>
<% end %>

<% if @report.taxon %>
  <p>
    <strong>This photo is actually of:</strong>
    <%= @report.taxon.common_name %> -- <%= @report.taxon.name %>
  </p>
<% end %>

<% if @report.no_herp %>
  <p>
    <strong>This photo doesn't have a herp in it...</strong>
  </p>
<% end %>


  </div>
</div>